### ISSUE TITLE
Better error handling based on errorCode

### ISSUE THREAD

**Issue by thomasthiebaud** [jaredly/f3d#2]
This is not really a bug, but a more general question about error with reason handling like you are doing here

https://github.com/jaredly/f3d/blob/41d5e7f1898654d55ff2c5e4edcfb98b8da72e84/src/Home/LogInPage.re#L58-L61

Firebase returns details in the error that I would like to access. Especially there is a field `code` that provide the kind of error. 

The corresponding bindings for this function looks like 

```
  [@bs.send]
  external signInWithEmailAndPassword:
    (t, ~email: string, ~password: string) => Js.Promise.t(User.t) =
    "signInWithEmailAndPassword";
```

Is there a way to specify in the bindings that the error will have a certain type ? So later on I can `switch` on the error code ?

The only piece of code that I was able to find is this one (https://github.com/bassjacob/bassjacob.com/blob/15d2b64eff04ead49b75f24d3676d83715eff7e5/src/cell.re)

```
external fromPromiseError: Js_promise.error => Express.Error.t = "%identity";

  let promiseControllerErrorHandler next => {
    Js_promise.catch (fun z => {
      z |> fromPromiseError
      |> Express.Next.error
      |> next
      |> Js.Promise.resolve
});
```

**Comment by jaredly** [comment]
Yeah doing an external to ceorce is definitely a way to do it, something like
```
type firebaseError = {"code": int, "message": string}; /* etc. */
external unsafeCeorceToFirebaseError: Js.Promise.error => firebaseError = "%identity";
```
But you might want to do some sanity checking on it first, to make sure that it does have a `code` attribute

**Comment by thomasthiebaud** [comment]
Awesome thanks. So there is no way to define the error type in the bindings directly ?

**Comment by jaredly** [comment]
The promise library doesn't currently support that. Also, in the case of javascript interop, it wouldn't be the most safe, because javascript could give you errors that don't conform to what you expect (a stackoverflow error, for example, or an exception in the firebase code)

**Comment by thomasthiebaud** [comment]
It makes a lot of sense indeed. Thanks a lot for the help
